### ISSUE TITLE
Run fails with "Disk write failure"

### ISSUE THREAD

**Issue by mydreamdoctor** [linuxatlas/atlas-server-docker#1]
I get the following error when attempting to run using the command provided in the readme.

Any ideas?

...
Redirecting stderr to '/home/wine/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
[----] Downloading update (0 of 13,269 KB)...
[  0%] Downloading update (1,871 of 13,269 KB)...
[ 14%] Downloading update (3,686 of 13,269 KB)...
[ 27%] Downloading update (5,102 of 13,269 KB)...
[ 38%] Downloading update (6,386 of 13,269 KB)...
[ 48%] Downloading update (7,673 of 13,269 KB)...
[ 57%] Downloading update (9,089 of 13,269 KB)...
[ 68%] Downloading update (10,375 of 13,269 KB)...
[ 78%] Downloading update (11,663 of 13,269 KB)...
[ 87%] Downloading update (13,079 of 13,269 KB)...
[ 98%] Downloading update (13,269 of 13,269 KB)...
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching...
Redirecting stderr to '/home/wine/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
ERROR! Failed to install app '1006030' (Disk write failure)

**Comment by linuxatlas** [comment]
What was the docker command you ran?

**Comment by mydreamdoctor** [comment]
Thanks for the reply.

I tried:
"docker run --rm -v /home/fred/atlas-server:/mnt/atlas-server atlas-server"

Thanks again.

**Comment by dimitrydeclercq** [comment]
Check permissions, it runs as the 'wine' user (uid 1001), probably not allowed to write to that path.

**Comment by linuxatlas** [comment]
I can make a build script that matches the user id. For now if you grab your user's ID via `echo $UID` or `id -u fred` then replace 1001 for your ID in the Dockerfile. Then rebuild the docker image.

**Comment by linuxatlas** [comment]
I just pushed a change to the README and Dockerfile that allows use of the user and group ID that's building the Dockerfile. This should mitigate the issue you ran into. Grab a fresh copy of the repository and follow the new build instructions.

**Comment by mydreamdoctor** [comment]
Thanks so much. Runs perfectly now.
